# Generated by Django 4.2.17 on 2026-02-12 08:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mandal",
                    models.CharField(
                        choices=[
                            ("machilipatnam", "Machilipatnam"),
                            ("gudivada", "Gudivada"),
                            ("vuyyur", "Vuyyur"),
                        ],
                        help_text="Select your mandal/region",
                        max_length=50,
                        verbose_name="Mandal (మండలం)",
                    ),
                ),
                (
                    "village",
                    models.CharField(
                        help_text="Enter your village name",
                        max_length=100,
                        verbose_name="Village (గ్రామం)",
                    ),
                ),
                (
                    "crop",
                    models.CharField(
                        choices=[
                            ("paddy", "Paddy (Rice)"),
                            ("mango", "Mango"),
                            ("chillies", "Chillies"),
                            ("cotton", "Cotton"),
                            ("turmeric", "Turmeric"),
                            ("sugarcane", "Sugarcane"),
                            ("banana", "Banana"),
                            ("tomato", "Tomato"),
                            ("okra", "Okra (Bhendi)"),
                            ("brinjal", "Brinjal (Eggplant)"),
                        ],
                        help_text="Select the crop you are growing",
                        max_length=50,
                        verbose_name="Crop Type (పంట రకం)",
                    ),
                ),
                (
                    "acres",
                    models.FloatField(
                        help_text="Total land area in acres",
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Total Acres (మొత్తం ఎకరాలు)",
                    ),
                ),
                (
                    "sowing_date",
                    models.DateField(
                        help_text="Date when crop was sown",
                        verbose_name="Sowing Date (విత్తిన తేదీ)",
                    ),
                ),
                (
                    "cold_storage",
                    models.BooleanField(
                        default=False,
                        help_text="Do you have access to cold storage/warehouse?",
                        verbose_name="Cold Storage Access (కోల్డ్ స్టోరేజ్)",
                    ),
                ),
                (
                    "urgent_cash",
                    models.BooleanField(
                        default=False,
                        help_text="Do you need urgent cash from this crop?",
                        verbose_name="Urgent Cash Need (తక్షణ నగదు అవసరం)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Farmer Record",
                "verbose_name_plural": "Farmer Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mandal",
                    models.CharField(
                        choices=[
                            ("machilipatnam", "Machilipatnam"),
                            ("gudivada", "Gudivada"),
                            ("vuyyur", "Vuyyur"),
                        ],
                        max_length=50,
                        verbose_name="Mandal",
                    ),
                ),
                (
                    "rainfall",
                    models.FloatField(
                        help_text="Rainfall in millimeters",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Rainfall (mm)",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        help_text="Average temperature in Celsius",
                        verbose_name="Temperature (°C)",
                    ),
                ),
                (
                    "humidity",
                    models.FloatField(
                        help_text="Relative humidity percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Humidity (%)",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Weather data date", verbose_name="Date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Weather Data",
                "verbose_name_plural": "Weather Data",
                "ordering": ["-date"],
                "unique_together": {("mandal", "date")},
            },
        ),
        migrations.CreateModel(
            name="PredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "predicted_yield",
                    models.FloatField(
                        help_text="Estimated total production in quintals",
                        verbose_name="Predicted Yield (Quintals)",
                    ),
                ),
                (
                    "yield_reduction_percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage reduction due to disease & weather",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Yield Reduction %",
                    ),
                ),
                (
                    "current_market_price",
                    models.FloatField(
                        help_text="Current price per quintal",
                        verbose_name="Current Market Price (₹/Q)",
                    ),
                ),
                (
                    "total_current_value",
                    models.FloatField(
                        help_text="Current total crop value (yield × current price)",
                        verbose_name="Total Current Value (₹)",
                    ),
                ),
                (
                    "predicted_peak_price",
                    models.FloatField(
                        help_text="Expected peak price per quintal",
                        verbose_name="Predicted Peak Price (₹/Q)",
                    ),
                ),
                (
                    "peak_price_date",
                    models.DateField(
                        blank=True,
                        help_text="Expected date for peak price",
                        null=True,
                        verbose_name="Peak Price Date",
                    ),
                ),
                (
                    "total_future_value",
                    models.FloatField(
                        help_text="Potential crop value at peak price",
                        verbose_name="Total Future Value (₹)",
                    ),
                ),
                (
                    "profit_delta",
                    models.FloatField(
                        help_text="Additional profit if waiting for peak price",
                        verbose_name="Extra Profit by Waiting (₹)",
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("store", "STORE - Wait for Better Price"),
                            ("sell", "SELL NOW - Immediate Sale Recommended"),
                        ],
                        help_text="Store or Sell Now decision",
                        max_length=20,
                        verbose_name="Final Recommendation",
                    ),
                ),
                (
                    "recommendation_reason",
                    models.TextField(
                        help_text="Explanation for the recommendation",
                        verbose_name="Recommendation Reason",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Prediction confidence level",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Confidence Score (%)",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Generated At"
                    ),
                ),
                (
                    "farmer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction",
                        to="forecast.farmer",
                        verbose_name="Farmer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prediction Result",
                "verbose_name_plural": "Prediction Results",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crop",
                    models.CharField(
                        choices=[
                            ("paddy", "Paddy (Rice)"),
                            ("mango", "Mango"),
                            ("chillies", "Chillies"),
                            ("cotton", "Cotton"),
                            ("turmeric", "Turmeric"),
                            ("sugarcane", "Sugarcane"),
                            ("banana", "Banana"),
                            ("tomato", "Tomato"),
                            ("okra", "Okra (Bhendi)"),
                            ("brinjal", "Brinjal (Eggplant)"),
                        ],
                        max_length=50,
                        verbose_name="Crop",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        help_text="Market location (e.g., Vijayawada, Guntur)",
                        max_length=100,
                        verbose_name="Region/Mandi",
                    ),
                ),
                (
                    "price_per_quintal",
                    models.FloatField(
                        help_text="Current market price in Rupees per quintal",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Price per Quintal (₹)",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date of price recording", verbose_name="Price Date"
                    ),
                ),
                (
                    "is_peak_season",
                    models.BooleanField(
                        default=False,
                        help_text="Is this peak price season?",
                        verbose_name="Peak Season",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Price",
                "verbose_name_plural": "Market Prices",
                "ordering": ["-date"],
                "unique_together": {("crop", "region", "date")},
            },
        ),
        migrations.CreateModel(
            name="DiseaseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disease_name",
                    models.CharField(
                        help_text="Name of detected disease (e.g., Rice Blast, Mango Anthracnose)",
                        max_length=200,
                        verbose_name="Disease Name (వ్యాధి పేరు)",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        help_text="Disease severity impact on yield",
                        max_length=20,
                        verbose_name="Severity Level (తీవ్రత స్థాయి)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload photo of affected leaf/fruit",
                        upload_to="crop_images/%Y/%m/%d/",
                        verbose_name="Crop Image",
                    ),
                ),
                (
                    "yield_loss_percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Estimated yield loss due to disease",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Yield Loss %",
                    ),
                ),
                (
                    "detection_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Detection Date"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Additional Notes"
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diseases",
                        to="forecast.farmer",
                        verbose_name="Farmer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease Record",
                "verbose_name_plural": "Disease Records",
                "ordering": ["-detection_date"],
            },
        ),
    ]
