# Generated by Django 4.2.17 on 2026-02-27 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forecast", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="farmer_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="diseaserecord",
            index=models.Index(
                fields=["-detection_date"], name="forecast_di_detecti_6dce15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diseaserecord",
            index=models.Index(
                fields=["severity"], name="forecast_di_severit_64bea8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmer",
            index=models.Index(
                fields=["-created_at"], name="forecast_fa_created_59b844_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmer",
            index=models.Index(
                fields=["mandal", "crop"], name="forecast_fa_mandal_bae581_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmer",
            index=models.Index(
                fields=["user", "-created_at"], name="forecast_fa_user_id_4a73bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketprice",
            index=models.Index(
                fields=["crop", "-date"], name="forecast_ma_crop_56ab73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketprice",
            index=models.Index(
                fields=["region", "-date"], name="forecast_ma_region_871485_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="predictionresult",
            index=models.Index(
                fields=["-generated_at"], name="forecast_pr_generat_0701df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="predictionresult",
            index=models.Index(
                fields=["recommendation"], name="forecast_pr_recomme_f91f64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weatherdata",
            index=models.Index(
                fields=["mandal", "-date"], name="forecast_we_mandal_8791fa_idx"
            ),
        ),
    ]
