# Generated by Django 4.2.17 on 2026-02-28 05:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forecast", "0002_farmer_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crop",
                    models.CharField(
                        choices=[
                            ("paddy", "Paddy (Rice)"),
                            ("mango", "Mango"),
                            ("chillies", "Chillies"),
                            ("cotton", "Cotton"),
                            ("turmeric", "Turmeric"),
                            ("sugarcane", "Sugarcane"),
                            ("banana", "Banana"),
                            ("tomato", "Tomato"),
                            ("okra", "Okra (Bhendi)"),
                            ("brinjal", "Brinjal (Eggplant)"),
                        ],
                        max_length=50,
                        verbose_name="Crop",
                    ),
                ),
                (
                    "target_price",
                    models.FloatField(
                        help_text="Alert when price reaches this level",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Target Price (₹/Q)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this alert currently active?",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_triggered",
                    models.BooleanField(
                        default=False,
                        help_text="Has this alert been triggered?",
                        verbose_name="Triggered",
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Triggered At"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Alert",
                "verbose_name_plural": "Price Alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="forecast_pr_user_id_eeecb8_idx",
                    ),
                    models.Index(
                        fields=["crop", "is_active"], name="forecast_pr_crop_fc17d9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("price_alert", "Price Alert"),
                            ("recommendation", "Crop Recommendation"),
                            ("weather_update", "Weather Update"),
                            ("system", "System Notification"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Has user read this notification?",
                        verbose_name="Read",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="forecast_no_user_id_032e49_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FavoriteCrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crop",
                    models.CharField(
                        choices=[
                            ("paddy", "Paddy (Rice)"),
                            ("mango", "Mango"),
                            ("chillies", "Chillies"),
                            ("cotton", "Cotton"),
                            ("turmeric", "Turmeric"),
                            ("sugarcane", "Sugarcane"),
                            ("banana", "Banana"),
                            ("tomato", "Tomato"),
                            ("okra", "Okra (Bhendi)"),
                            ("brinjal", "Brinjal (Eggplant)"),
                        ],
                        max_length=50,
                        verbose_name="Crop",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_crops",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite Crop",
                "verbose_name_plural": "Favorite Crops",
                "ordering": ["crop"],
                "unique_together": {("user", "crop")},
            },
        ),
    ]
